chore: print containers on failure

diff --git a/.github/workflows/im-build-test-deploy.yaml b/.github/workflows/im-build-test-deploy.yaml
--- a/.github/workflows/im-build-test-deploy.yaml
+++ b/.github/workflows/im-build-test-deploy.yaml
@@ -191,9 +191,17 @@ jobs:
 
       - name: Confirm ${{ inputs.HEALTH_CHECK_ENDPOINT }} returns 200
         run: |
-          docker ps --all
-          docker compose logs prod
-          timeout 1m bash -c 'until curl --silent --fail localhost:8080${{ inputs.HEALTH_CHECK_ENDPOINT }}; do sleep 2; done'
+          (timeout 1m bash -c 'until curl --silent --fail localhost:8080${{ inputs.HEALTH_CHECK_ENDPOINT }}; do sleep 2; done')
+          exit_code=$?
+          if [ $exit_code -ne 0 ]; then
+            echo "Healthcheck failed with exit code $exit_code"
+            docker ps --all
+            docker compose logs prod
+            exit $exit_code
+          else
+            echo "Healthcheck succeeded"
+            exit 0
+          fi
 
       - name: Confirm process isn't running as root
         run: |
